/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author hnebe
 */
public class MainScreen extends javax.swing.JFrame {

	ProjectController projectController;
	TaskController taskController;
	DefaultListModel projectsModel; 
	TaskTableModel taskModel;
	TaskEditDialogScreen taskEditDialogScreen;
	
	
	public MainScreen() {
		initComponents();
		initDataController();
		initComponentsModel();
		decorateTableTasks();
		int taskId;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPaneTasks = new javax.swing.JScrollPane();
                jTableTasks = new javax.swing.JTable();
                JpanelToolBar = new javax.swing.JPanel();
                jLabelToolBarTitle = new javax.swing.JLabel();
                jLabelToolBarSubTitle = new javax.swing.JLabel();
                jLabelIcon = new javax.swing.JLabel();
                jPanelProjects = new javax.swing.JPanel();
                jLabelProjectsTitle = new javax.swing.JLabel();
                jLabelProjectsIcon = new javax.swing.JLabel();
                jPanelTasks = new javax.swing.JPanel();
                jLabelTasksTitle = new javax.swing.JLabel();
                jLabelTasksIcon = new javax.swing.JLabel();
                jPanelProjectList = new javax.swing.JPanel();
                jScrollPaneProjects = new javax.swing.JScrollPane();
                jListProjects = new javax.swing.JList<>();
                jPanel5 = new javax.swing.JPanel();
                jPanelEmptyTasks = new javax.swing.JPanel();
                jLabelEmptyListIcon = new javax.swing.JLabel();
                jLabelEmptyListSubTitle = new javax.swing.JLabel();
                jLabelEmptyListTitle = new javax.swing.JLabel();

                jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null}
                        },
                        new String [] {
                                "Nome", "Descrição", "Prazo", "Tarefa Concluída", "Title 5", "Title 6"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, true, true, true
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jTableTasks.setGridColor(new java.awt.Color(255, 255, 255));
                jTableTasks.setRowHeight(30);
                jTableTasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
                jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTableTasksMouseClicked(evt);
                        }
                });
                jScrollPaneTasks.setViewportView(jTableTasks);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(600, 600));

                JpanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

                jLabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabelToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabelToolBarTitle.setText("TodoAPP");

                jLabelToolBarSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelToolBarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabelToolBarSubTitle.setText("Anote tudo! Não esqueça de nada!");

                jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N

                javax.swing.GroupLayout JpanelToolBarLayout = new javax.swing.GroupLayout(JpanelToolBar);
                JpanelToolBar.setLayout(JpanelToolBarLayout);
                JpanelToolBarLayout.setHorizontalGroup(
                        JpanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpanelToolBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JpanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelToolBarSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(JpanelToolBarLayout.createSequentialGroup()
                                                .addComponent(jLabelIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                JpanelToolBarLayout.setVerticalGroup(
                        JpanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpanelToolBarLayout.createSequentialGroup()
                                .addGroup(JpanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JpanelToolBarLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabelIcon))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelToolBarLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelToolBarTitle)
                                                .addGap(8, 8, 8)))
                                .addComponent(jLabelToolBarSubTitle)
                                .addContainerGap(14, Short.MAX_VALUE))
                );

                jPanelProjects.setBackground(new java.awt.Color(255, 255, 255));
                jPanelProjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

                jLabelProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabelProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
                jLabelProjectsTitle.setText("Projetos");

                jLabelProjectsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
                jLabelProjectsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelProjectsIconMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelProjectsLayout = new javax.swing.GroupLayout(jPanelProjects);
                jPanelProjects.setLayout(jPanelProjectsLayout);
                jPanelProjectsLayout.setHorizontalGroup(
                        jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProjectsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelProjectsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanelProjectsLayout.setVerticalGroup(
                        jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProjectsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelProjectsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanelTasks.setBackground(new java.awt.Color(255, 255, 255));
                jPanelTasks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

                jLabelTasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabelTasksTitle.setForeground(new java.awt.Color(0, 153, 102));
                jLabelTasksTitle.setText("Tarefas");

                jLabelTasksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
                jLabelTasksIcon.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelTasksIconMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
                jPanelTasks.setLayout(jPanelTasksLayout);
                jPanelTasksLayout.setHorizontalGroup(
                        jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTasksLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTasksIcon)
                                .addContainerGap())
                );
                jPanelTasksLayout.setVerticalGroup(
                        jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTasksLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelTasksIcon))
                                .addContainerGap())
                );

                jPanelProjectList.setBackground(new java.awt.Color(255, 255, 255));
                jPanelProjectList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

                jListProjects.setBorder(null);
                jListProjects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jListProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jListProjects.setFixedCellHeight(30);
                jListProjects.setSelectionBackground(new java.awt.Color(0, 153, 102));
                jListProjects.setSelectionForeground(new java.awt.Color(255, 255, 255));
                jListProjects.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jListProjectsMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                jListProjectsMouseEntered(evt);
                        }
                });
                jScrollPaneProjects.setViewportView(jListProjects);

                javax.swing.GroupLayout jPanelProjectListLayout = new javax.swing.GroupLayout(jPanelProjectList);
                jPanelProjectList.setLayout(jPanelProjectListLayout);
                jPanelProjectListLayout.setHorizontalGroup(
                        jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );
                jPanelProjectListLayout.setVerticalGroup(
                        jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneProjects, javax.swing.GroupLayout.Alignment.TRAILING)
                );

                jPanel5.setBackground(new java.awt.Color(255, 255, 255));
                jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
                jPanel5.setLayout(new java.awt.BorderLayout());

                jPanelEmptyTasks.setBackground(new java.awt.Color(255, 255, 255));

                jLabelEmptyListIcon.setBackground(new java.awt.Color(255, 255, 255));
                jLabelEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelEmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

                jLabelEmptyListSubTitle.setBackground(new java.awt.Color(255, 255, 255));
                jLabelEmptyListSubTitle.setForeground(new java.awt.Color(102, 102, 102));
                jLabelEmptyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelEmptyListSubTitle.setText("Click no botão + para adicionar uma nova tarefa!");

                jLabelEmptyListTitle.setBackground(new java.awt.Color(255, 255, 255));
                jLabelEmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelEmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
                jLabelEmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelEmptyListTitle.setText("Nenhuma tarefa por aqui!");

                javax.swing.GroupLayout jPanelEmptyTasksLayout = new javax.swing.GroupLayout(jPanelEmptyTasks);
                jPanelEmptyTasks.setLayout(jPanelEmptyTasksLayout);
                jPanelEmptyTasksLayout.setHorizontalGroup(
                        jPanelEmptyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEmptyListSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addComponent(jLabelEmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanelEmptyTasksLayout.setVerticalGroup(
                        jPanelEmptyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEmptyTasksLayout.createSequentialGroup()
                                .addContainerGap(162, Short.MAX_VALUE)
                                .addComponent(jLabelEmptyListIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEmptyListTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEmptyListSubTitle)
                                .addContainerGap(171, Short.MAX_VALUE))
                );

                jPanel5.add(jPanelEmptyTasks, java.awt.BorderLayout.CENTER);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JpanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(JpanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jLabelProjectsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjectsIconMouseClicked
                ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
		projectDialogScreen.setVisible(true);
		
		projectDialogScreen.addWindowListener(new WindowAdapter(){
			
			public void windowClosed(WindowEvent e){
				loadProjects();
			}
		});
        }//GEN-LAST:event_jLabelProjectsIconMouseClicked

        private void jLabelTasksIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTasksIconMouseClicked
                TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
		
		int projectIndex = jListProjects.getSelectedIndex();
		Project project = (Project) projectsModel.get(projectIndex);
		taskDialogScreen.setProject(project);
		
		taskDialogScreen.setVisible(true);
		
		taskDialogScreen.addWindowListener(new WindowAdapter(){
			
			public void windowClosed(WindowEvent e){
				
				int projectIndex = jListProjects.getSelectedIndex();
				Project project = (Project) projectsModel.get(projectIndex);
				loadTasks(project.getId());
			}
		});
        }//GEN-LAST:event_jLabelTasksIconMouseClicked

        private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
                
		int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
		int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
		Task task = taskModel.getTasks().get(rowIndex);
		jTableTasks.setToolTipText(task.getNotes());
		
		
		switch(columnIndex){
			
			case 3 -> {
				try {
					taskController.update(task);
					break;
				} catch (Exception ex) {
					Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
				}
			}

			case 4 -> {TaskEditDialogScreen taskEditDialogScreen = new TaskEditDialogScreen(this, rootPaneCheckingEnabled);
		
				int projectIndex = jListProjects.getSelectedIndex();
				Project project = (Project) projectsModel.get(projectIndex);
				taskEditDialogScreen.setProject(project);
				taskEditDialogScreen.setTask(task);
				taskEditDialogScreen.jTextAreaDescription.setText(task.getDescription());
				taskEditDialogScreen.jTextPaneNotes.setText(task.getNotes());
				taskEditDialogScreen.jTextPaneName.setText(task.getName());
				SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
				String deadline = dateFormat.format(task.getDeadline());
				
				
				taskEditDialogScreen.jFormattedTextFieldDeadLine.setText(deadline);
				taskEditDialogScreen.setVisible(true);
				
				

				taskEditDialogScreen.addWindowListener(new WindowAdapter(){
			
			public void windowClosed(WindowEvent e){
				
				int projectIndex = jListProjects.getSelectedIndex();
				Project project = (Project) projectsModel.get(projectIndex);
				loadTasks(project.getId());
			}
		});
				
			break;}
			
			case 5 -> {
				try {
					taskController.removeById(task.getId());
					taskModel.getTasks().remove(task);
				int projectIndex = jListProjects.getSelectedIndex();
				Project project = (Project) projectsModel.get(projectIndex);
				loadTasks(project.getId());
				break;
				} catch (Exception ex) {
					Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
				
				

		}
		
        }//GEN-LAST:event_jTableTasksMouseClicked

        private void jListProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjectsMouseClicked
              
	int projectIndex = jListProjects.getSelectedIndex();
	Project project = (Project)projectsModel.get(projectIndex);
	jListProjects.setToolTipText(project.getDescription());
	loadTasks(project.getId());
        }//GEN-LAST:event_jListProjectsMouseClicked

        private void jListProjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjectsMouseEntered
       
        }//GEN-LAST:event_jListProjectsMouseEntered

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Java swing".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainScreen().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel JpanelToolBar;
        private javax.swing.JLabel jLabelEmptyListIcon;
        private javax.swing.JLabel jLabelEmptyListSubTitle;
        private javax.swing.JLabel jLabelEmptyListTitle;
        private javax.swing.JLabel jLabelIcon;
        private javax.swing.JLabel jLabelProjectsIcon;
        private javax.swing.JLabel jLabelProjectsTitle;
        private javax.swing.JLabel jLabelTasksIcon;
        private javax.swing.JLabel jLabelTasksTitle;
        private javax.swing.JLabel jLabelToolBarSubTitle;
        private javax.swing.JLabel jLabelToolBarTitle;
        private javax.swing.JList<String> jListProjects;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanelEmptyTasks;
        private javax.swing.JPanel jPanelProjectList;
        private javax.swing.JPanel jPanelProjects;
        private javax.swing.JPanel jPanelTasks;
        private javax.swing.JScrollPane jScrollPaneProjects;
        private javax.swing.JScrollPane jScrollPaneTasks;
        private javax.swing.JTable jTableTasks;
        // End of variables declaration//GEN-END:variables
	
	public void decorateTableTasks(){
	
	//customizando o header da table de tarefas	
	jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
	jTableTasks.getTableHeader().setBackground(new Color(0, 153, 102));
	jTableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
	//customizando as colunas
	jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
	jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
	jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
	//criando um sorter automatico 
	//jTableTasks.setAutoCreateRowSorter(rootPaneCheckingEnabled);
	
	
	} 
	
	public void initDataController(){
		projectController = new ProjectController();
		taskController = new TaskController();
		taskModel = new TaskTableModel();
		jTableTasks.setModel(taskModel);
		
		
	}
	
	public void initComponentsModel(){
		projectsModel = new DefaultListModel();
		loadProjects();
		
		
		if (!projectsModel.isEmpty()) {
		jListProjects.setSelectedIndex(0);
		int projectIndex = jListProjects.getSelectedIndex();
		Project project = (Project) projectsModel.get(projectIndex);
		
	        loadTasks(project.getId());
		
        }
		
	}
	
	public void loadTasks(int idProject){
		List<Task> tasks = taskController.getAll(idProject);
		taskModel.setTasks(tasks);
		
		showJTableTasks(!tasks.isEmpty());
		
	}
	
	
	private void showJTableTasks(boolean hasTasks) {
        if (hasTasks) {
            if (jPanelEmptyTasks.isVisible()) {
                jPanelEmptyTasks.setVisible(false);
                jPanel5.remove(jPanelEmptyTasks);
            }

            jPanel5.add(jScrollPaneTasks);
            jScrollPaneTasks.setVisible(true);
            jScrollPaneTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        } else {
            if (jScrollPaneTasks.isVisible()) {
                jScrollPaneTasks.setVisible(false);
                jPanel5.remove(jScrollPaneTasks);
            }

            jPanel5.add(jPanelEmptyTasks);
            jPanelEmptyTasks.setVisible(true);
            jPanelEmptyTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
    }

	
	public void loadProjects(){
		List<Project> projects = projectController.getAll();
		
		projectsModel.clear();
		
		for(int i = 0; i<projects.size(); i++){
			
			Project project = projects.get(i);
			
			projectsModel.addElement(project);
		
		
		}
		jListProjects.setModel(projectsModel);
		
	}

	
}
