/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author hnebe
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

	
	ProjectController controller;
	
	public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		controller = new ProjectController();
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelToolbar = new javax.swing.JPanel();
                jLabelToolBarTitle = new javax.swing.JLabel();
                jLabelToolBarSave = new javax.swing.JLabel();
                jPanelProject = new javax.swing.JPanel();
                jLabelName = new javax.swing.JLabel();
                jTextFieldName = new javax.swing.JTextField();
                jLabelDescription = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextPaneDescription = new javax.swing.JTextPane();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanelToolbar.setBackground(new java.awt.Color(0, 153, 102));
                jPanelToolbar.setForeground(new java.awt.Color(255, 255, 255));

                jLabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabelToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabelToolBarTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabelToolBarTitle.setText("Projeto");

                jLabelToolBarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
                jLabelToolBarSave.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelToolBarSaveMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelToolbarLayout = new javax.swing.GroupLayout(jPanelToolbar);
                jPanelToolbar.setLayout(jPanelToolbarLayout);
                jPanelToolbarLayout.setHorizontalGroup(
                        jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolbarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelToolBarSave)
                                .addContainerGap())
                );
                jPanelToolbarLayout.setVerticalGroup(
                        jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelToolBarSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jLabelToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jPanelProject.setBackground(new java.awt.Color(255, 255, 255));

                jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelName.setText("Nome");

                jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextFieldName.setForeground(new java.awt.Color(0, 153, 102));
                jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

                jLabelDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelDescription.setText("Descrição");

                jTextPaneDescription.setForeground(new java.awt.Color(0, 153, 102));
                jScrollPane1.setViewportView(jTextPaneDescription);

                javax.swing.GroupLayout jPanelProjectLayout = new javax.swing.GroupLayout(jPanelProject);
                jPanelProject.setLayout(jPanelProjectLayout);
                jPanelProjectLayout.setHorizontalGroup(
                        jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addGroup(jPanelProjectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldName))
                                .addContainerGap())
                );
                jPanelProjectLayout.setVerticalGroup(
                        jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProjectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jLabelToolBarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolBarSaveMouseClicked
                
		
		
		try {
		if(jTextFieldName.getText().equals("")){
			JOptionPane.showMessageDialog(rootPane,"Projeto não foi salvo. Insira um nome para salvar o projeto!");}
			
		else{Project project = new Project();
			project.setName(jTextFieldName.getText());
		project.setDescription(jTextPaneDescription.getText());
			controller.save(project);
			JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!");
			this.dispose();}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(rootPane,"Erro ao salvar o projeto" + ex);
		}
		
		
		
        }//GEN-LAST:event_jLabelToolBarSaveMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Java swing".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
			ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
			dialog.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
				public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelName;
        private javax.swing.JLabel jLabelToolBarSave;
        private javax.swing.JLabel jLabelToolBarTitle;
        private javax.swing.JPanel jPanelProject;
        private javax.swing.JPanel jPanelToolbar;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextFieldName;
        private javax.swing.JTextPane jTextPaneDescription;
        // End of variables declaration//GEN-END:variables
}
