/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author hnebe
 */
public class TaskDialogScreen extends javax.swing.JDialog {

	TaskController taskController;
	Project project;
	
	public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		HideMessageError();
		taskController = new TaskController();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelToolBar = new javax.swing.JPanel();
                jLabelTitle = new javax.swing.JLabel();
                jLabelSave = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabelName = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextPaneName = new javax.swing.JTextPane();
                jLabelDescription = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextAreaDescription = new javax.swing.JTextArea();
                jLabelDeadLine = new javax.swing.JLabel();
                jFormattedTextFieldDeadLine = new javax.swing.JFormattedTextField();
                jLabelNotes = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextPaneNotes = new javax.swing.JTextPane();
                jLabelDeadLineError = new javax.swing.JLabel();
                jLabelNameError = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

                jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabelTitle.setText("Tarefa");

                jLabelSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
                jLabelSave.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelSaveMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
                jPanelToolBar.setLayout(jPanelToolBarLayout);
                jPanelToolBarLayout.setHorizontalGroup(
                        jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelToolBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSave)
                                .addContainerGap())
                );
                jPanelToolBarLayout.setVerticalGroup(
                        jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelSave, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelName.setText("Nome");

                jTextPaneName.setForeground(new java.awt.Color(0, 153, 102));
                jScrollPane1.setViewportView(jTextPaneName);

                jLabelDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelDescription.setText("Descrição");

                jTextAreaDescription.setColumns(20);
                jTextAreaDescription.setForeground(new java.awt.Color(0, 153, 102));
                jTextAreaDescription.setRows(5);
                jScrollPane2.setViewportView(jTextAreaDescription);

                jLabelDeadLine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelDeadLine.setText("Prazo");

                jFormattedTextFieldDeadLine.setForeground(new java.awt.Color(0, 153, 102));
                jFormattedTextFieldDeadLine.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

                jLabelNotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabelNotes.setText("Notas");

                jTextPaneNotes.setForeground(new java.awt.Color(0, 153, 102));
                jScrollPane3.setViewportView(jTextPaneNotes);

                jLabelDeadLineError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabelDeadLineError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelDeadLineError.setText("*CAMPO OBRIGATÓRIO");

                jLabelNameError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabelNameError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelNameError.setText("*CAMPO OBRIGATÓRIO");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelDeadLineError)
                                                .addGap(0, 310, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabelNameError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelNotes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelDeadLine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jFormattedTextFieldDeadLine))
                                                .addContainerGap())))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNameError)
                                .addGap(1, 1, 1)
                                .addComponent(jLabelDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDeadLine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDeadLineError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNotes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jLabelSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSaveMouseClicked
                
		try { if(isValidText()){
		Task task = new Task();
		
		task.setIdProject(project.getId());
		task.setName(jTextPaneName.getText());
		task.setDescription(jTextAreaDescription.getText());
		task.setNotes(jTextPaneNotes.getText());
		task.setIsCompleted(false);
		//data!!!!
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		Date deadline = null;
		deadline = dateFormat.parse(jFormattedTextFieldDeadLine.getText());
		task.setDeadline(deadline);
		//data!!!
		
			taskController.save(task);
			JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!");
			this.dispose();
			 
		}else{
			HideMessageError();
			if (jTextPaneName.getText().equals("")){ 
			jLabelNameError.setVisible(true);}
			if (jFormattedTextFieldDeadLine.getText().isEmpty()){
			jLabelDeadLineError.setVisible(true);
			}}
			
		
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(rootPane,"Erro ao salvar a tarefa!");
		}
		
		
        }//GEN-LAST:event_jLabelSaveMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFormattedTextField jFormattedTextFieldDeadLine;
        private javax.swing.JLabel jLabelDeadLine;
        private javax.swing.JLabel jLabelDeadLineError;
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelName;
        private javax.swing.JLabel jLabelNameError;
        private javax.swing.JLabel jLabelNotes;
        private javax.swing.JLabel jLabelSave;
        private javax.swing.JLabel jLabelTitle;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanelToolBar;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTextArea jTextAreaDescription;
        private javax.swing.JTextPane jTextPaneName;
        private javax.swing.JTextPane jTextPaneNotes;
        // End of variables declaration//GEN-END:variables

	public void setProject(Project project) {
		this.project = project;
	}

	public void HideMessageError(){
		jLabelDeadLineError.setVisible(false);
		jLabelNameError.setVisible(false);
	}
	
	public boolean isValidText(){
		
		if(!jTextPaneName.getText().equals("") && !jFormattedTextFieldDeadLine.getText().isEmpty()){
		return true;}
		else return false;
	}

	
}

